eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    server-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
